# Generated by Django 5.2.10 on 2026-02-01 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_patientprofile_id_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPERADMIN', 'Super Admin'), ('SHOP', 'Shop'), ('DOCTOR', 'Doctor'), ('PATIENT', 'Patient')], max_length=20),
        ),
    ]
