# Generated by Django 5.2.10 on 2026-02-01 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorshopconnection',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='medicalshop',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
